# config.toml
# In this project, we use this TOML file for all the configurations.
[DataLoader]
data_root = "data/VOCdevkit/VOC2012"
openimages_dir = "/Volumes/T7_Shield/Datasets"
batch_size = 64
img_size = 640
num_workers = 0

[OpenImages]
images_dir = "data/OpenImagesV7/images"
annotations_file = "data/OpenImagesV7/relationships.csv"
batch_size = 16
img_size = 640
num_workers = 0

[Trainer]
init_lr = 1e-4
min_lr = 1e-6
weight_decay = 0.0005
epochs = 50
grad_clip = 5.0
output_dir = "results/trained_models"
save_interval = 5

[Logic_Tensor_Networks]
mlp_input_dim = 24
mlp_hidden_dims = [128, 64]
mlp_dropout = 0.1
cnn_input_dim = 24
cnn_channels = [16, 32]
cnn_unflatten = [8, 8]
conv_kernel_size = 3
pool_size = 2
default_threshold = 0.7

[OneFormer_Extractor]
processor = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
model = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
cache_dir = "cache_pretrained"
conf_threshold = 0.25
mask_threshold = 0.25
task_inputs = "panoptic"

[YOLO_Extractor]
model_path = "cache_pretrained/yolo11n-seg.pt"
conf_threshold = 0.25
