# config.toml
# In this project, we use this TOML file for all the configurations.

[Train]
lr = 0.001
epochs = 450
batch_size = 16384

[Trainer]
relationships_path = "/Volumes/T7_Shield/Datasets/relationships.json"
image_meta_path = "/Volumes/T7_Shield/Datasets/image_data.json"

lr_factor = 0.8
lr_patience = 10
lr_min = 1e-5


[OneFormer_Extractor]
processor = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
model = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
cache_dir = "cache_pretrained"
conf_threshold = 0.25
mask_threshold = 0.25
task_inputs = "panoptic"

[YOLO_Extractor]
model_path = "cache_pretrained/yolo11n-seg.pt"
conf_threshold = 0.25
