# config.toml
# In this project, we use this TOML file for all the configurations.

[Train]
lr = 0.001
epochs = 1000
batch_size = 2048

[Trainer]
relationships_path = "/root/autodl-tmp/relationships_full.json"
image_meta_path = "/root/autodl-tmp/image_data_full.json"

patience = 100
lr_factor = 0.8
lr_patience = 30
lr_min = 1e-5


[OneFormer_Extractor]
processor = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
model = "./cache_pretrained/models--shi-labs--oneformer_ade20k_swin_large/snapshots/4a5bac8e64f82681a12db2e151a4c2f4ce6092b2"
cache_dir = "cache_pretrained"
conf_threshold = 0.1
mask_threshold = 0.1
task_inputs = "panoptic"

[YOLO_Extractor]
model_path = "cache_pretrained/yolo11n-seg.pt"
conf_threshold = 0.25
